export const posts = [
  {
    id: "1",
    postName: "Forest",
    liked: "13",
    src: "https://source.unsplash.com/2ShvY8Lf6l0/800x599",
    width: 4,
    height: 3,
  },
  {
    id: "2",
    postName: "Mashroom",
    liked: "7",
    src: "https://source.unsplash.com/Dm-qxdynoEc/800x799",
    width: 1,
    height: 1,
  },
  {
    id: "3",
    postName: "Inspiration",
    liked: "15",
    src: "https://source.unsplash.com/qDkso9nvCg0/600x799",
    width: 3,
    height: 4,
  },
  {
    id: "4",
    postName: "Reever",
    liked: "11",
    src: "https://source.unsplash.com/iecJiKe_RNg/600x799",
    width: 3,
    height: 4,
  },
  {
    id: "5",
    postName: "Leafs",
    liked: "10",
    src: "https://source.unsplash.com/epcsn8Ed8kY/600x799",
    width: 3,
    height: 4,
  },
  {
    id: "6",
    postName: "Misty",
    liked: "9",
    src: "https://source.unsplash.com/NQSWvyVRIJk/800x599",
    width: 4,
    height: 3,
  },
  {
    id: "7",
    postName: "Lorem Ipusm",
    liked: "2",
    src: "https://source.unsplash.com/zh7GEuORbUw/600x799",
    width: 3,
    height: 4,
  },
  {
    id: "8",
    postName: "Lorem Ipusm",
    liked: "12",
    src: "https://source.unsplash.com/PpOHJezOalU/800x599",
    width: 4,
    height: 3,
  },
  {
    id: "9",
    postName: "Lorem Ipusm",
    liked: "10",
    src: "https://source.unsplash.com/I1ASdgphUH4/800x599",
    width: 4,
    height: 3,
  },
  {
    id: "10",
    postName: "Lorem Ipusm",
    liked: "8",
    src: "https://source.unsplash.com/XiDA78wAZVw/600x799",
    width: 3,
    height: 4,
  },
  {
    id: "11",
    postName: "Lorem Ipusm",
    liked: "4",
    src: "https://source.unsplash.com/x8xJpClTvR0/800x599",
    width: 4,
    height: 3,
  },
  {
    id: "12",
    postName: "Lorem Ipusm",
    liked: "3",
    src: "https://source.unsplash.com/qGQNmBE7mYw/800x599",
    width: 4,
    height: 3,
  },
  {
    id: "13",
    postName: "Lorem Ipusm",
    liked: "23",
    src: "https://source.unsplash.com/NuO6iTBkHxE/800x599",
    width: 4,
    height: 3,
  },
  {
    id: "14",
    postName: "Lorem Ipusm",
    liked: "20",
    src: "https://source.unsplash.com/pF1ug8ysTtY/600x400",
    width: 4,
    height: 3,
  },
  {
    id: "15",
    postName: "Lorem Ipusm",
    liked: "28",
    src: "https://source.unsplash.com/A-fubu9QJxE/800x533",
    width: 4,
    height: 3,
  },
  {
    id: "16",
    postName: "Lorem Ipusm",
    liked: "30",
    src: "https://source.unsplash.com/5P91SF0zNsI/740x494",
    width: 4,
    height: 3,
  },
];
